spring:
  application:
    name: card-management-service

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000

app:
  encryption:
    secret-key: ${APP_ENCRYPTION_SECRET_KEY}
